// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izctgsufbxlbxxvhzaxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Y3Rnc3VmYnhsYnh4dmh6YXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzY3NTAsImV4cCI6MjA3MzAxMjc1MH0.zGKwHLXVp7rI5hfjRiti5LsHQI5LI2MSOecalum2ilw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});